services:
  neo4j:
    image: neo4j:latest
    container_name: oln-neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password # Change in production
    volumes:
      - /Volumes/hellastuff 1/oln/neo4j/data:/data
      - /Volumes/hellastuff 1/oln/neo4j/logs:/logs
    restart: always

  temporal:
    image: temporalio/admin-tools:latest
    container_name: oln-temporal-tools
    depends_on:
      - temporal-server
    environment:
      - TEMPORAL_ADDRESS=temporal-server:7233

  temporal-server:
    image: temporalio/auto-setup:latest
    container_name: oln-temporal-server
    ports:
      - "7233:7233"
    environment:
      - DB=postgresql
      - POSTGRES_SEEDS=temporal-postgres
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_DB=temporal
    volumes:
      - /Volumes/hellastuff 1/oln/temporal/data:/var/lib/temporal
    restart: always

  temporal-postgres:
    image: postgres:latest
    container_name: oln-temporal-postgres
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_DB=temporal
    volumes:
      - /Volumes/hellastuff 1/oln/temporal/postgres-data:/var/lib/postgresql/data
    restart: always

  temporal-ui:
    image: temporalio/ui:latest
    container_name: oln-temporal-ui
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal-server:7233
    depends_on:
      - temporal-server
    restart: always

  redis:
    image: redis:latest
    container_name: oln-redis
    ports:
      - "6379:6379"
    volumes:
      - /Volumes/hellastuff 1/oln/redis/data:/data
    restart: always
